- name: Setup WordPress Web Server
  hosts: wordpress
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: install Apache, PHP, and other dependencies
      yum:
        name:
          - httpd
          - php
          - php-mysqlnd
          - wget
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes

    - name: download latest wordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: extract wordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        extra_opts: ["--strip-components=1"]

    - name: Set permissions on /var/www/html
      file:
        path: /var/www/html
        state: directory
        recurse: yes
        owner: apache
        group: apache
        mode: '0755'

    - name: Create wp-config.php from template
      template:
        src: wp-config.php.j2
        dest: /var/www/html/wp-config.php
